language: minimal

before_deploy:
  - docker build -t janniswarnat/gpsd-faker:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker push janniswarnat/gpsd-faker:latest
    on:
      branch: master