version: '3.3'
services:
  gpsfaker1:
    image: "janniswarnat/gpsd-faker"
    volumes:
      - ./config.json:/gpsd-faker/config.json
    environment:
      - PUBLISH_EVERY=5
      - MQTT_URL=mqtts://***:8883
      - TRACKER_ID=XV
      - MQTT_USERNAME=***
      - MQTT_PASSWORD=***
